[project]
name = "rialto"
version = "2.1.5"
description = "Rialto is a framework for building and deploying machine learning features in a scalable and reusable way. It provides a set of tools that make it easy to define and deploy features and models, and it provides a way to orchestrate the execution of these features and models."
authors = [
    { name = "Marek Dobransky", email = "marekdobr@gmail.com" },
    { name = "Vladislav Vancak", email = "vladislav.vancak@gmail.com" },
]
requires-python = ">=3.11, <4.0"
readme = "README.md"
keywords = [
    "feature",
    "featureslib",
    "featuremaker",
    "metadata",
    "featureloader",
    "loader",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic>=2.12.3,<3",
    "pathlib>=1.0.1,<2",
    "pyyaml>=6.0.3,<7",
    "delta-spark>=4.0.0,<5",
    "python-dateutil>=2.9.0.post0,<3",
    "pytest-mock>=3.15.1,<4",
    "pandas>=2.3.3,<3",
    "flake8-broken-line>=1.0.0,<2",
    "loguru>=0.7.3,<0.8",
    "importlib-metadata>=8.7.0,<9",
    "numpy>=2.3.4,<3",
]

[project.urls]
Repository = "https://github.com/AbsaOSS/rialto"
Documentation = "https://absaoss.github.io/rialto/"

[dependency-groups]
dev = [
    "pyspark>=4.0.0,<5",
    "chispa>=0.11.1,<0.12",
    "pytest>=8.4.2,<9",
    "black>=25.9.0,<26",
    "isort>=7.0.0,<8",
    "pytest-cov>=7.0.0,<8",
    "flake8>=7.3.0,<8",
    "flake8-docstrings>=1.7.0,<2",
    "pep8-naming>=0.15.1,<0.16",
    "pre-commit>=4.3.0,<5",
    "sphinx>=8.2.3,<9",
    "sphinx-rtd-theme>=3.0.2,<4",
    "sphinx-mdinclude>=0.6.2,<0.7",
]

[tool.hatch.build.targets.sdist]
include = ["rialto"]

[tool.hatch.build.targets.wheel]
include = ["rialto"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.isort]
profile = "black"
