name: Testing

on:
  pull_request:
    branches: [ master, develop ]

env:
  LANG: C.UTF-8

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rialto
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: "8"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.5
        with:
          poetry-version: 1.5.1

      - name: Install dependencies
        run: |
          poetry install

      - name: ✅ Test with pytest
        run: |
          poetry run pytest
