name: Testing

on:
  pull_request:
    branches: [ master, develop ]

env:
  LANG: C.UTF-8

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rialto
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: "21"

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: ✅ Test with pytest
        run: |
          uv run pytest
