name: Release

on:
  push:
    branches: [ master ]

env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  publish:
    environment:
      name: pypi
      url: https://pypi.org/p/rialto
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rialto
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build the wheel
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
