name: Merge to develop

on:
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git pull
          git checkout develop
          git pull
          git merge --ff-only master
          git push
