name: Release

on:
  push:
    branches: [ master ]

env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Rialto
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.5
        with:
          poetry-version: 1.5.1

      - name: Install dependencies
        run: |
          poetry install

      - name: Build and publish the wheel to jfrog
        run: |
          poetry build
          twine upload dist/*
